.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. icocoin_qt test_icocoin_qt
clean: FORCE
	$(MAKE) -C .. icocoin_qt_clean test_icocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_icocoin_qt_check
icocoin-qt icocoin-qt.exe: FORCE
	 $(MAKE) -C .. icocoin_qt
